routes/web.php
<?php

Route::group(['middleware' => ['web']], function(){
  // Page

  Route::get('/', [ 'uses' => 'PageController@welcome', 'as' => 'welcome' ]);
  Route::get('show-article/{id}', ['uses' => 'PageController@show', 'as' => 'show-article']);
  Route::get('blog', ['uses' => 'PageController@blog', 'as' => 'blog']);
  Route::get('dashboard', ['uses' => 'PageController@dashboard', 'as' => 'dashboard', 'middleware' => 'auth' ]);
  Route::get('about', ['uses' => 'PageController@about', 'as' => 'about']);
  Route::get('contact', ['uses' => 'PageController@contact', 'as' => 'contact']);
  Route::get('profil', ['uses' => 'PageController@getProfil', 'as' => 'profil']);

  // foto profil & cover
  Route::get('gantifoto', ['uses' => 'PageController@gantifoto', 'as' => 'gantifoto']);
  Route::post('profil', ['uses' => 'PageController@postProfil', 'as' => 'profil']);
  Route::post('cover', ['uses' => 'PageController@postCover', 'as' => 'cover']);

  // User
  Route::post('signup', ['uses' => 'UserController@postSignUp', 'as' => 'signup']);
  Route::get('signup', function(){ return view('page.signup');});
  Route::post('signin', ['uses' => 'UserController@postSignIn', 'as' => 'signin']);
  Route::get('admin', ['middleware' => 'admin', function(){
    echo "admin";
  }]);
  Route::get('signin', function(){ return view('page.login'); } );
  Route::get('edit/{id}', [ 'uses' => 'UserController@getEdit', 'as' => 'edit' ]);
  Route::post('edit/{id}', [ 'uses' => 'UserController@postEdit', 'as' => 'edit' ]);

  Route::get('pedit/{id}', [ 'uses' => 'UserController@getPedit', 'as' => 'pedit' ]);
  Route::post('pedit/{id}', [ 'uses' => 'UserController@postPedit', 'as' => 'pedit' ]);

  Route::get('logout', ['uses' => 'UserController@logout', 'as' => 'logout']);
  Route::get('delete/{id}', ['uses' => 'UserController@destroy', 'as' => 'delete']);

  // Post
  Route::resource('posts', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Post;
use Session;

class PostController extends Controller
{
  public function __construct() {
        $this->middleware('auth');
    }

  public function index()
  {
    // create a variable and store all the blog posts in it from the database
    $posts = Post::OrderBy('created_at', 'desc')->paginate(5);

    // return a view and pass in the above variable
    return view('posts.index')->with('posts', $posts);

  }

  public function create()
  {
    return view('posts.create');
  }

  public function store(Request $request)
  {
    // validate the DOMCdataSection
    $this->validate($request, [
      'title' =>  'required|max:255',
      'body'  =>  'required'
    ]);

    // store to the database
    $post = new Post;
    $post->title  = $request->title;
    $post->body   = $request->body;

    $post->save();
    Session::flash('success', 'The blog post was successfully save !' );
    return redirect()->route('posts.show', $post->id);
  }

  public function show($id)
  {
    $posts = Post::find($id);
    return view('posts.show')->with('post', $posts);
  }

  public function edit($id)
  {
    $post = Post::find($id);
    return view('posts.edit')->with('posts', $post);
  }

  public function update(Request $request, $id)
  {
        // Validate the data
    $post = Post::find($id);

    if ($request->input('slug') == $post->slug) {
        $this->validate($request, [
        'title' =>  'required|max:255',
        'body'  =>  'required'
      ]);
    }
    else {
      $this->validate($request, [
        'title' =>  'required|max:255',
        // 'slug'  =>  'required|alpha_dash|min:5|max:255|unique:posts,slug',
        'body'  =>  'required'
      ]);
    }

    // Save the data to the database
    $post = Post::find($id);

    $post->title = $request->input('title');
    // $post->slug  = $request->input('slug');
    $post->body = $request->input('body');
    $post->save();

    Session::flash('success', 'the post was successfully updated');

    // redirect to another page
    return redirect()->route('posts.show', $post->id);
    // redirect view with flash message to posts.show
  }

  public function destroy($id)
  {
    $post = Post::find($id);
    $post->delete();
    Session::flash('success', 'The pos was successfully deleted');
    return redirect()->route('posts.index');
  }
}

resources/views/posts/create.blade.php
@extends('layout.master')
@section('title')
  SantriNgoding - Create new post
@endsection

@section('konten')
  <div class="row">
    <div class="col-md-8 col-md-offset-2 ">
      <h1>Create new Post</h1>
      <hr>
      {!! Form::open(['route' => 'posts.store', 'data-parsley-validate' => '']) !!}
        {{ Form::label('title', 'Title : ') }}
        {{ Form::text('title', null, ['class' => 'form-control', 'required' => '']) }}

        {{ Form::label('body', 'Body : ') }}
        <div id="summernote"><p>Hello Summernote</p></div>
        <script>
          $(document).ready(function() {
              $('#summernote').summernote();
          });
        </script>
        {{ Form::submit('Create Post', ['class' => 'btn btn-primary btn-block', 'style' => 'margin-top:20px;']) }}
      {!! Form::close() !!}
    </div>
  </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layout.master')
@section('title')
  SantriNgoding - Edit posting
@endsection
@section('konten')
<div class="content">
    <div class="row">
    {!! Form::model($posts, ['route' => ['posts.update', $posts->id], 'method' => 'PUT' ]) !!}
    <div class="col-md-8">
      {{ Form::label('title', 'Judul') }}
      {{ Form::text('title', null, ['class' => 'form-control input-lg']) }}

      {{ Form::label('body', 'Konten', ['class' => 'form-spacing-top']) }}
      {{ Form::textarea('body', null, ['class' => 'form-control']) }}


    </div>
    <div class="col-md-4" style="margin-top: 25px;">
      <div class="well">
        <dl class="dl-horizontal">
          <dt>Tanggal dibuat :</dt>
          <dd>{{ date('H:i M j, Y', strtotime($posts->created_at)) }}</dd>
        </dl>

        <dl class="dl-horizontal">
          <dt>Terakhir diperbarui :</dt>
          <dd>{{ date('H:i M j, Y', strtotime($posts->updated_at)) }}</dd>
        </dl>

        <hr>
        <div class="row">
          <div class="col-sm-6">
            {!! Html::linkRoute('posts.show', 'Batal', [$posts->id], ['class' => 'btn btn-danger btn-block']) !!}
          </div>

          <div class="col-sm-6">
            {{ Form::submit('Simpan perubahan', ['class' => 'btn btn-success btn-block']) }}
          </div>
        </div>
      </div>
    </div>
    {!! Form::close() !!}
  </div> <!-- end of .row -->
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layout.master')
@section('title')
  SantriNgoding - Post Dashboard
@endsection
@section('konten')
  <div class="row">
    <div class="col-md-10">
      <h1 style="margin-left: 10px;">Semua posting</h1>
    </div>
    <div class="col-md-2">
      {!! Html::linkRoute('posts.create', 'Buat posting baru', [null], ['class' => 'btn btn-lg btn-block btn-warning', 'style' => 'margin-top:20px;']) !!}
    </div>
    <div class="col-md-12">
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-condensed">
        <thead>
          <th> # </th>
          <th>Judul</th>
          <th>Konten</th>
          <th>Tanggal dibuat</th>
          <th></th>
        </thead>
        <tbody>
          @foreach($posts as $post)
            <tr>
              <td>{{ $post->id }}</td>
              <td>{{ $post->title }}</td>
              <td>{{ substr(strip_tags($post->body), 0, 50) }} {{ strlen(strip_tags($post->body)) > 50 ? "..." : "" }}</td>
              <td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
              <td>
                <a href="{{ route('posts.destroy', $post->id) }}"  class="btn-primary btn"><i class="glyphicon glyphicon-eye-open"></i></a>
                <a href="{{ route('posts.edit', $post->id) }}" class="btn-info btn"><i class="glyphicon glyphicon-pencil"></i></a>
              </td>
            </tr>
            <tr></tr>
          @endforeach
        </tbody>
      </table>
      <div class="text-center">
        {!! $posts->links() !!}
      </div>
    </div>
  </div>
@endsection

resources/views/posts/show.blade.php
@extends('layout.master')
@section('title')
  SantriNgoding - Lihat posting
@endsection
@section('konten')
<div class="content">

<div class="row">
  <div class="col-md-8">
    <h1>{{ $post->title }}</h1>
    <p class="lead">
      {!!  $post->body !!}
    </p>
  </div>

  <div class="col-md-4">
    <div class="well">

      <dl class="dl-horizontal">
        <label><strong>Tanggal dibuat :</strong></label>
        <p>{{ date('H:i M j, Y', strtotime($post->created_at)) }}</p>
      </dl>

      <dl class="dl-horizontal">
        <label><strong>Terakhir diperbarui :</strong></label>
        <p>{{ date('H:i M j, Y', strtotime($post->updated_at)) }}</p>
      </dl>

      <hr>
      <div class="row">
        <div class="col-sm-6">

          {!! Html::linkRoute('posts.edit', 'Edit', [$post->id], ['class' => 'btn btn-primary btn-block']) !!}
        </div>

        <div class="col-sm-6">
          {!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}

            {!! Form::submit('Hapus', ['class' => 'btn btn-danger btn-block']) !!}

          {!! Form::close() !!}
        </div>
      </div>
      <div class="row">
        <div class="col-md-12" style="margin-top: 10px;">
          <a href="{{ route('posts.index') }}" class="btn btn-default btn-block">Kembali</a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection