routes/web.php
<?php

Route::group(['middleware' => ['web']], function(){
  // Page

  Route::get('/', [ 'uses' => 'PageController@welcome', 'as' => 'welcome' ]);
  Route::get('show-article/{id}', ['uses' => 'PageController@show', 'as' => 'show-article']);
  Route::get('blog', ['uses' => 'PageController@blog', 'as' => 'blog']);
  Route::get('dashboard', ['uses' => 'PageController@dashboard', 'as' => 'dashboard', 'middleware' => 'auth' ]);
  Route::get('about', ['uses' => 'PageController@about', 'as' => 'about']);
  Route::get('contact', ['uses' => 'PageController@contact', 'as' => 'contact']);
  Route::get('profil', ['uses' => 'PageController@getProfil', 'as' => 'profil']);

  // foto profil & cover
  Route::get('gantifoto', ['uses' => 'PageController@gantifoto', 'as' => 'gantifoto']);
  Route::post('profil', ['uses' => 'PageController@postProfil', 'as' => 'profil']);
  Route::post('cover', ['uses' => 'PageController@postCover', 'as' => 'cover']);

  // User
  Route::post('signup', ['uses' => 'UserController@postSignUp', 'as' => 'signup']);
  Route::get('signup', function(){ return view('page.signup');});
  Route::post('signin', ['uses' => 'UserController@postSignIn', 'as' => 'signin']);
  Route::get('admin', ['middleware' => 'admin', function(){
    echo "admin";
  }]);
  Route::get('signin', function(){ return view('page.login'); } );
  Route::get('edit/{id}', [ 'uses' => 'UserController@getEdit', 'as' => 'edit' ]);
  Route::post('edit/{id}', [ 'uses' => 'UserController@postEdit', 'as' => 'edit' ]);

  Route::get('pedit/{id}', [ 'uses' => 'UserController@getPedit', 'as' => 'pedit' ]);
  Route::post('pedit/{id}', [ 'uses' => 'UserController@postPedit', 'as' => 'pedit' ]);

  Route::get('logout', ['uses' => 'UserController@logout', 'as' => 'logout']);
  Route::get('delete/{id}', ['uses' => 'UserController@destroy', 'as' => 'delete']);

  // Post
  Route::resource('posts', 'PostController');
});

resources/views/include/article.blade.php
@foreach($post as $post)
 <div class="panel panel-flat">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <article>
          <h4 style="color: black;">{{ $post->title }}</h4>
            <p> Posted on <font style="color: #00BFA5">{{ date('M j, Y', strtotime($post->created_at)) }} </font></p>
          <hr>
          <h6>
            {!! substr(strip_tags($post->body), 0, 200) !!} {{ strlen(strip_tags($post->body)) > 200 ? "..." : "" }}
            @if(Auth::guest())
              <a href="{{ route('show-article', $post->id) }}">Read More &rarr;</a>
              @else
                <a href="{{ route('posts.show', $post->id) }}">Read More &rarr;</a>
            @endif
          </h6>
        </article>
      </div>
    </div>
  </div>
</div>
@endforeach

resources/views/include/footer.blade.php
<!-- Footer  -->
<div class=" footer text-muted content-right ">
&copy; 2016. <a href="#">Web Developer Team</a> by <a href="http://facebook.com/afrijal.dzuhri" target="_blank">Afrijal Dzuhri</a>
</div>
<!-- /footer -->

resources/views/include/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@yield("title")</title>

<!-- Global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/core.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/components.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/colors.css') }}" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->

<!-- favicon -->
<link rel="shortcut icon" href="{{ asset('assets/images/favicon.png') }}">

<!-- Core JS files -->
<script type="text/javascript" src="{{ asset('assets/js/plugins/loaders/pace.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/libraries/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/loaders/blockui.min.js') }}"></script>
@include('include.js')
<!-- /core JS files -->

<!-- Theme JS files -->
<script type="text/javascript" src="{{ asset('assets/js/plugins/visualization/d3/d3.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/visualization/d3/d3_tooltip.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/switchery.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/moment/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/pickers/daterangepicker.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
{{-- <script type="text/javascript" src="{{ asset('assets/js/pages/dashboard.js') }}"></script> --}}
<!-- /theme JS files -->

{{-- font --}}
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

resources/views/include/header.blade.php
	  <!-- Main navbar -->
	  <div class="navbar navbar-inverse">
		  <div class="navbar-header">
			  <a class="navbar-brand" href="/"><img src="assets/images/logo_light.png" alt=""></a>
        <ul class="nav navbar-nav visible-xs-block">
				  <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
			    <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
			   </ul>
		  </div>
	  </div>
	  <!-- /main navbar -->

resources/views/include/js.blade.php
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
 <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
 <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
 <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.css" rel="stylesheet">
 <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>

resources/views/include/mainnavbar.blade.php
<div class="navbar navbar-inverse" >
  <div class="navbar-header">
    @if (Auth::guest())
    <a class="navbar-brand" href="{{ route('welcome') }}"><img src="{{ asset('assets/images/logo_light.png') }}" alt=""></a>
    @else
    <a class="navbar-brand" href="{{ route('blog') }}"><img src="{{ asset('assets/images/logo_light.png') }}" alt=""></a>
    <ul class="nav navbar-nav">
        <li class="{{ Request::is('/about') ? "active" : "" }}"><a href="{{ route('about')}}">Tentang</a></li>
        <li class="{{ Request::is('/contact') ? "active" : "" }}"><a href="{{ route('contact') }}">Kontak</a></li>
    </ul>
    <ul class="nav navbar-nav visible-xs-block">
      <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
      <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
    </ul>
   </div>

  <div class="navbar-collapse collapse" id="navbar-mobile">
	  <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <img src="/uploads/avatars/{{ Auth::user()->avatar }}" style="width:32px; height:32px; potision:absolute; top:10px; margin-right:5px;  border-radius:50%;"/>
          {{ Auth::user()->nama }} <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('profil') }}">Profil</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="{{ route('posts.index') }}">Posting</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="{{ route('edit', Auth::user()->id) }}">Pengaturan</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="{{ route('logout') }}">Keluar</a></li>
        </ul>
      </li>
	  </ul>
	</div>
  @endif
</div>
</div>

resources/views/include/message.blade.php
@if(Session::has('success'))
  <div class="alert alert-success" role="alert" style="margin-top: 10px;">
    <strong>Success : </strong> {{ Session::get('success') }}
  </div>
@endif
@if(Session::has('error'))
  <div class="alert alert-danger" role="alert" style="margin-top: 10px;">
    <strong>Error : </strong> {{ Session::get('error') }}
  </div>
@endif
@if(count($errors) > 0)
  <div class="alert alert-danger" role="alert">
    @foreach($errors->all() as $error)
      <ul>
        <li>        {{ $error }}      </li>
      </ul>
    @endforeach
  </div>
@endif

resources/views/include/pageheader.blade.php
<!-- Page header -->
<div class="page-header">
  <div class="page-header-content">
    <div class="page-title">
      <h4></i> <span class="text-semibold">Home</span> - Dashboard</h4>
    </div>

    <div class="heading-elements">
      <div class="heading-btn-group">

      </div>
    </div>
  </div>

</div>